spring.application.name=pro2kf2026
server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3307/pro2kf2026?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=heslo123

hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=update

